[package]
name = "rust-nn"
version = "0.1.0"
authors = ["Tucker Morgan <tucker.bull.morgan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
ndarray = "0.13.0"